# Extra hardware-specific configuration
{...}: {
  # Hardware fan control
  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon1=devices/pci0000:00/0000:00:18.3 hwmon6=devices/platform/nct6775.656
      DEVNAME=hwmon1=k10temp hwmon6=nct6779
      FCTEMPS=hwmon6/pwm2=hwmon1/temp1_input hwmon6/pwm3=hwmon1/temp1_input
      FCFANS=hwmon6/pwm2=hwmon6/fan2_input
      MINTEMP=hwmon6/pwm2=50 hwmon6/pwm3=50
      MAXTEMP=hwmon6/pwm2=85 hwmon6/pwm3=85
      MINSTART=hwmon6/pwm2=30 hwmon6/pwm3=30
      MINSTOP=hwmon6/pwm2=20 hwmon6/pwm3=20
    '';
  };

  # Don't let fancontrol block rebuilds
  systemd.services.fancontrol.unitConfig.X-StopOnReconfiguration = false;

  # Load sensor modules for fancontrol
  boot.kernelModules = ["k10temp" "nct6775"];
}
